### ISSUE TITLE
HttpClient should ignore HttpInterceptor chain when calling Prismic CDN

### ISSUE THREAD

**Issue by heavybeard** [exportarts/ngx-prismic#23]

**Comment by heavybeard** [comment]
Where to change the behavior -> https://github.com/exportarts/ngx-prismic/blob/72f90771f6fb7fb7a5c808a95df4f01d4f69efba/lib/prismic-client/src/services/prismic.service.ts#L58

How change the behavior -> https://stackoverflow.com/a/49013534

I'll try to create a PR

**Comment by evolkmann** [comment]
Hi @heavybeard this is a good point. I would appreciate it if you can provide a PR as I will not be available over the weekend. If you don't find the time, I can take a look at it next week.

**Comment by heavybeard** [comment]
@evolkmann This issue is returned. I'll create a new PR with the same fix in the same place.
